### ISSUE TITLE
Missing way to donate / pay

### ISSUE THREAD

**Issue by nextsux** [hufman/AndroidAutoIdrive#129]
Hi @hufman,

this project is AWESOME. It works better than original integration with spotify (which was canceled). **I absolutely love it**. Is there a way I can make you a donation? I think many spotify users are searching for a way how to make ConnectedDrive integration working and would love to donate for this!

**Comment by hufman** [comment]
I'm so glad to hear that you are enjoying it!
The main README page has a link to [![Buy Me A Coffee](https://img.shields.io/badge/support-buymeacoffee-5f7fff)](https://www.buymeacoffee.com/q4JVoxz), which is the main way I've set up to receive donations, due to its small dollar amount and hopefully easy process!
Additionally, the app will show a one-time popup on the 5th day of successful car connections to ask for support and links to this same page, but it only shows that one single time.

I plan on a big Phone UI revamp for the next version, and I will link this issue to adding a donate link to the app itself.
Thank you again for your support!

**Comment by nextsux** [comment]
sorry about that - I suppose I'm totally blind. I really looked for that button and just have not seen it. After grepping raw over `README.md` i've discovered it :rofl:

**Comment by bogdan-calapod** [comment]
Hey,

I was just "rummaging" through the issue and stumbled upon this one. I've made a quick mockup of what a "donate" page in the app might look like, with the new UI revamp (#81):

![image](https://user-images.githubusercontent.com/5462727/97199930-43464780-17b9-11eb-8af6-523647c73235.png)

I tried to also emphasize that people aren't forced to donate, and they can enjoy the app and help in other ways as well.

I put it in the bottom tab bar for now, but I want to rethink that screen so we can put it somewhere not as prominent if you think it would be better :D

**Comment by kvphani** [comment]
This app is perfect way to fix the missing Spotify integration after their latest mess with android version. Thanks a ton for the developer and the new UI looks great.
