### ISSUE TITLE
Google Maps notification integration

### ISSUE THREAD

**Issue by bogdan-calapod** [hufman/AndroidAutoIdrive#131]
The current GMaps integration is nice, but a bit too limited because:
* It can't be integrated in the main APK due to licensing limitations
* It can't be used as a navi UI due to licensing limitations
* Most people don't build their own APK, they use already available ones.

A workaround that currently exists is to select the Google Maps notification from the active notifications list and keep it focused. This provides useful info such as:
* Next turn info
* Distance 'till next turn
* ETA

While not ideal (e.g. no map view available) this is better than nothing (especially for folks like me without navi on their cars 😅).

A stepgap until #43 is done could be a new car app that parses the information from the notification like so:
![image](https://user-images.githubusercontent.com/5462727/96279252-1470ea00-0fdf-11eb-86f5-069448fa3fae.png)

This could also work with the HUD display, integrating navigation instructions before/after the current track display, so the order would be something like:

* ... prev tracks
* < Back
* Navi info
* Current track
* Next >
* ... next tracks

I think this would bring a huge improvement on the experience in car 😁 In the future we could also add a live map view based on the location of the car, via some free service like OpenStreetMap or the above mentioned MapBox (#43)

I can help further with the UI design, as well as think up some config screen for this feature if needed.

**Comment by bogdan-calapod** [comment]
An improvement that I mentioned in other issues but will post here as well so we have everything in one place:

If the user selects the `Google Maps` app in the car with no active Google Maps navigation running, it would be nice if we could allow a selection of locations (e.g. Home, Work, etc.) that would trigger a navigation on the phone.

These could be either set manually in the app, or pulled from Google Maps' Favorites list.

**Comment by jezikk82** [comment]
Hi, I'm not sure if it's connected by when I compiled yesterday version to test this integration I notices as below:
1. I lost images in map module (instead of the map I see only with image with Google logo bottom-left). Strange... Before It worked OK. 
2. When I start navi on the phone with app connected to the car I dont see this directions, only "standard" notification as it was previously. Any comments?

**Comment by hufman** [comment]
Good afternoon! This issue is just around improving the display of the Google Maps notification, with 1.3 milestone having just the basic notification improvements and future possibilities with an embedded map for the future 1.4 milestone. The only  difference you'll notice so far is that the Google Maps navigation (on the phone) will show up with a larger arrow.
This issue specifically relates to the official Google Maps app on the phone. The built-in Maps functionality hasn't been modified. Verify that your Google API key is still set up right, and check for any log output in `adb logcat` to see if it is rejecting the key for some reason.
![photo5582485431077939116](https://user-images.githubusercontent.com/1592375/99581389-94e78980-2995-11eb-9cdc-acd337cba5df.jpg)
