### ISSUE TITLE
Is there a way to simulate a connected car when developing?

### ISSUE THREAD

**Issue by kohner86** [hufman/AndroidAutoIdrive#14]
Great work on this project, I've been toying with the idea of something like this but looks like you beet me to the punch!

Would love to contribute but one issue I'm running into is that my car is parked in an underground garage (no cell reception and quite far from my desktop computer) which means running/debugging the app is going to be a bit of a pain, is there any sort of simulator/test harness to I could use to test some of my code?  I see you have a branch started for voice input which is something I'd be interested in helping out with.

**Comment by kohner86** [comment]
Nvm, found the tests.

**Comment by hufman** [comment]
Thank you for your interest in contributing! The tests should help a lot with verifying certain aspects of functionality, indeed. I don't have any good automated integration tests, however. I would like to rewrite the tests to make the user event inputs clearer and more succinct, instead of the current verbose mess.
Since the protocol is just talking to an Apache Etch server, you could make a basic car-side implementation of some parts of the protocol. I have one that I use for occasional experiments, but it's not complete enough or accurate enough for me to want to release it.

Please reach out with any further questions or suggestions!

**Comment by kohner86** [comment]
Thanks, just getting a feel for the code now, I've got a WIP branch cleaning up the names of the Spotify custom actions, maybe done in a week or so: https://github.com/hufman/AndroidAutoIdrive/compare/master...kohner86:master
