### ISSUE TITLE
Bug: Shortcut to Music app stays in idle forever

### ISSUE THREAD

**Issue by christiancloudical** [hufman/AndroidAutoIdrive#147]
Hey,

first of all, it is fu**ing awesome, that this is even existant :D Thank your for that!

Did a quick testing with my ID6 Nav Prof 12/16.
Connection works, spotify works quite good, some other apps are recognized but useless ( f.e. Radio Bob - Can't do anything in Idrive, but when I start a radio stream, it is played on BMW and screen shows stream info a.s.o. ) 
Used stable version 1.22
The only real issue has been recognized with selecting an "app" directly. For Spotify, it directly switched audio source and started playing, but Icon staied in that "wheel turning idle state".

I updated to master, will check again if this is still an issue, when I am back in my car

Thanks for that awesome work!

**Comment by hufman** [comment]
Happy good morning! Thank you so much for the kind words :)
You'll be happy to know that the spinning app icons was fixed in efdcd74, one of the many exciting improvements you'll find in the master build!
As for Radio Bob, I was able to add browse support for it in 18a2fdb just now, so the latest build also includes that feature for you :)

**Comment by christiancloudical** [comment]
Awesome xD That was quick :+1:
