### ISSUE TITLE
Support for new My BMW App

### ISSUE THREAD

**Issue by Wuerstchenfinger** [hufman/AndroidAutoIdrive#149]
Just asking because I am curious. Is it possible (and or planed) to support the new MyBMW App?

Link to App: https://play.google.com/store/apps/details?id=de.bmw.connected.mobile20.row

PS Thank you for your great work!

**Comment by hufman** [comment]
Hello! Thanks for the question.
The current version (1.2.0) of the My BMW app includes most of the code to run the BMW Apps connection to the car (the BCL tunnel and the various accessory connection listeners), but it is not currently enabled (the BaseA4AApplication module is omitted). I've added support for the Security Module in this new My BMW app, so if the BMW Apps connection is enabled in the future, it should just work automatically with this single app.

If you are using IDrive 4-6, it should be safe to have both My BMW and BMW Connected installed at the same time. The main problem with combining Connected and Connected Classic is that both apps would try talking directly to the car, with undefined results and sometimes headunit crashes. Since My BMW isn't currently talking the BMW Apps protocol, this problem shouldn't happen.

If using IDrive 7, the car doesn't support BMW Apps anyways, but there is a risk that the latest BMW Connected and My BMW apps will both try to use a special BMW Bluetooth protocol to bootstrap the Android Auto Wifi-Direct connection, and I have no idea how the car will react to that.

Hope this helps answer your question!

**Comment by Wuerstchenfinger** [comment]
Hi!

Tested it today. Sadly it is not working. If I have both BMW apps installed (BMW Connected App and the new MyBMW App) AndroidAutoIdrive cannot connect.

Here are my first things I noticed:

1. Both BMW Apps will show a notification that they are connected to my Car.
2. AndroidAutoIdrive will not show that it is connected.
3. AndroidAutoIdrive tries to connect but fails with `Handshake Failed`
4. To make it working again I needed to reinstall AndroidAutoIdrive, restart my Phone, restart my infotainment system and deinstall the myBMW App.

Additional information:

- BMW F31 340i (2019) with Professional Navi

If you want to dig deeper in this problem and need more info, i will gladly help.

**Comment by hufman** [comment]
Alas, this is at the BMW App level, and AndroidAutoIdrive can't offer any help here. The Handshake Failed message is coming from BMW Connected, specifically the module that runs the BCL tunnel, so it's probably encountering interference from My BMW trying to start up the newer protocol over the same Bluetooth connection.

You should just need to uninstall My BMW and then Connected should automatically work on the next connection.

I guess they interfere more than I thought :(
