### ISSUE TITLE
Spotify Information on home screen

### ISSUE THREAD

**Issue by Sven31415** [hufman/AndroidAutoIdrive#150]
First of all I want to thank hufman for his great work, I nearly bought an iPhone because of my car, but now I can stay with the good phones :)
Now to the "issue": I have a NBT Evo headunit(id6 (light?))
On the home screen (pressing menu) the original spotify App has shown the track information(cover, artist, ...)
Now this is just a blank field. Is there something that can be done?
I can add a picture later, if one is needed

**Comment by hufman** [comment]
Happy weekend! I'm happy you are enjoying it!
I believe this blank information might be related to #93: When the IDrive Spotify integration is running, and when this app is controlling Spotify, then Spotify itself will also try to update the car's global multimedia information with its own AudioHmiState widgets. However, because this app (as Audioplayer) is the one in control of the music, the car gets confused and tries to show the incorrect empty Multimedia widget. This can be confirmed by switching to a different music app, because then the official Spotify will stop trying to update the metadata and the other music app's metadata will be displayed.

The current best recommendation is to update Spotify to the latest version to disable its native IDrive interface. This will allow the Audioplayer's Multimedia Info widget to be displayed, which should hold the correct information. Additionally, if you are running the latest build (as opposed to the latest release version 1.2.2), then the app will log in as Spotify itself, allowing the app to display global cover art using the new AudioHmiState widgets (#59).

Did I understand the situation correctly? Let me know if that suggestion helped!

**Comment by Sven31415** [comment]
Hi thanks for the very fast answer,
tou did understand the issue perfectly :)
As you have described other music apps are able to show the information on the home screen (tested it before).
But I haven't tried to switch back to spotify again so I can't say if the information is visible then.
I don't like the idea if updating spotify to the latest version, because then I won't be able to scroll through my songs anymore. (?)
I use the nightly builds, so when I get back in to my car I will try the option to have your app logging in as Spotify. Is "global cover art" this what I mean so the information on the homescreen? 

Please keep up your great work, I now have to get more into all this stuff and at least find out how to support you by donating (I think I've already read something about that)

**Comment by hufman** [comment]
Thank you so much, I greatly appreciate your willingness to test out the latest builds!
This app supports using Spotify's remote control API to browse your library, beyond using the ancient version of Spotify that allowed browsing through the native Android API. If you are using the latest build and the Browse menu shows cover art, this confirms that it is using the Spotify API to browse and it is safe to upgrade to the latest version. Of course, this API is only able to connect to an unmodified Spotify.

Logging in as Spotify is only enabled by default if a new-enough Spotify is installed, to prevent adding a duplicate icon or adding a Spotify icon if the user doesn't have Spotify installed. By enabling the advanced option for force Spotify mode, the user won't be surprised about any unexpected Spotify icons :)

Global Cover Art is the main visible feature of this AudioHmiState feature, which can show the app's coverart in the main menu and the Multimedia side panel, along with a progress bar. This information isn't able to be set with the old Audioplayer mode, which can only set two lines of text (currently Artist and Title).

Thank you so much for the kind words and support!
