### ISSUE TITLE
Google Assistant for Voice Control

### ISSUE THREAD

**Issue by kohner86** [hufman/AndroidAutoIdrive#18]
I've been experimenting with adding a way for the user to trigger the google assistant voice prompt: https://github.com/hufman/AndroidAutoIdrive/compare/master...kohner86:master#diff-1c29cab35fd57bfdea68ca5f0a671c98

The above largely works but the UX seems a little wonky so I was thinking of putting it in its own 'App' within IDrive (still trying to figure out that part of the API).

**Comment by hufman** [comment]
Ah, that's a clever way to hide arbitrary extra actions, I like it!
Making a new separate App in IDrive is tricky, because the location and icon are hardcoded by what certificate is used to log in to the car. You can see the existing resources I'm using inside the `assets/carapplications` directory. You can find other certificates inside other BMW Connected Apps around on apkpure and ipahub, but your custom app will need to use whatever icon (and if you enable it, text strings) that comes with that app.
If you just want to trigger an event with just a single button press, the `am_registerApp` might be an interesting path forward: It lets you create any arbitrary menu entry with custom icon (48px square PNG) and text label in the Music or Connected Apps list and register a callback for a button press. It's meant to be a placeholder icon to trigger a full application to load and replace the placeholder icon, but `AVContextHandler` shows an example of abusing that feature for other purposes :)

I see that some cars mention a speech2text capability, but my current car doesn't implement it so I can't experiment with it yet. The car has some sort of passthrough in use for the Apple Siri feature, but I haven't yet explored how to trigger the same input screen.
There are references to `iSpeechSupport` in the resource files, but I don't see any code in the official apps that touches it.

**Comment by hufman** [comment]
![image](https://user-images.githubusercontent.com/1592375/77385841-8da8a700-6d46-11ea-98f4-ddcafd985347.png)
Initial testing seems hopeful, I don't know if it's using the phone microphone or the car's microphone though.

**Comment by hufman** [comment]
Ah, there is an option in the Google Assistant itself to enable Bluetooth recording!
Under Hands-Free, the app requires "Allow Bluetooth requests with the device locked" and works better with "Bluetooth audio recording".
![image](https://user-images.githubusercontent.com/1592375/77387610-1cb7be00-6d4b-11ea-921a-698ebe0e0b71.png)

**Comment by ziggythehamster** [comment]
On my USDM car which I've coded to have Speech2Text, the only discernable change is that SMS gives me a reply option. If I use that option, it asks me to subscribe to Dragon Drive, which I'm not confident will work so haven't.

This is not the same UI as nav > POI > online search > voice

**Comment by hufman** [comment]
I haven't figured out what the speech2text feature means specifically.. I wonder if it's related to the Input screen, which on IDrive5+ has an extra entry in the rotary wheel to prompt to record a voice clip and convert the speech to the inputted text.
I haven't experimented with coding at all, however.

**Comment by hufman** [comment]
<img src="https://user-images.githubusercontent.com/1592375/85243226-24dcd380-b3f6-11ea-8678-bcfbc00858ce.png" height="400" title="Screenshot of Assistant Feature" />

Any detected assistants (responding to the `Intent.VOICE_COMMAND` Intent) will be added to the ConnectedDrive menu in the car. My Pixel2 (with Android 9) can reliably trigger the assistant, but my Galaxy S9 (running Android 10, perhaps subject to [these rules](https://developer.android.com/guide/components/activities/background-starts)) can only trigger it while the AndroidAutoIdrive app is visible on screen.
I have a wrench icon to (try to) link to the Google Assistant Voice Preferences, which is helpful to enable Bluetooth Audio Recording and to Allow Requests With Device Locked.
Only Google currently supports recording from Bluetooth, Alexa and Bixby and Cortana do not. When the app is set to record from Bluetooth, it nicely switches the car to show that it's recording External Input, otherwise the car just shows "Starting App" even though the app is working.
Also, only Google and Bixby currently seem to make a prompting noise to indicate that they are listening.

Can I request that some people try out [this dev build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/391/391.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2.1-30-fc83d3f-fc83d3f689ae65512506cffcb0eec991fd60dade-nomap-nonalytics-release.apk) and see how it works for them?

**Comment by hufman** [comment]
Please try out [this new build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/394/394.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2.1-30-104217b-104217bfa6110c35119998078dbe6f33d22f123c-nomap-nonalytics-release.apk), which includes a workaround for Android 10 devices. My Galaxy S9 seems to work very nicely with it.
