### ISSUE TITLE
App does not close connection to Spotify

### ISSUE THREAD

**Issue by fabssor** [hufman/AndroidAutoIdrive#217]
Again thanks for the great work! I notice some kind of bug:
Since the newest nightly builds, I noticed that AndroidAutoIDrive does not close the connection to Spotify when the Bluetooth connection to the car is closed.
This is noticeable by the fact that Spotify displays a notification that I can not remember 100% but something like: "AndroidAutoIDrive is connected to Spotify".
The notification goes away if I (force) kill the AndroidAutoIdrive app.

Spotify Version: 8.6.2.774
AndoirdAutoIdrive Version: 1.2.2-371-e6592cf

Thanks! :)

**Comment by kvphani** [comment]
I have the same problem, where the notification - "AndroidAutoIDrive is connected to Spotify" is still showing even after the BMW app and this app are both disconnected from the car. Currently, I am force stopping Spotify to remove this notification.
 I am using Spotify version 8.6.4.971 (but the issue was even with previous Spotify versions)
AndroidAutoIdrive version 1.2.2-369

**Comment by hufman** [comment]
I believe the latest build should fix this, please test and confirm!

**Comment by fabssor** [comment]
After some time it worked for me but switched to "optimized mode" in battery settings for spotfiy.

**Comment by hufman** [comment]
Seems like it is still happening

**Comment by hufman** [comment]
I just pushed a probable fix, try it out!

**Comment by hufman** [comment]
Could you try out a branch build, [this branch](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-spotify_singleton-nomap-sentry-release.apk) which converts the Spotify logic to use a single client instead of running several clients.
You could also test out a different branch build, [this branch](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-spotify_upgrade-nomap-sentry-release.apk) merely upgrades to a newer Spotify SDK version, to see if it helps this issue.
Let me know what you find!

**Comment by kvphani** [comment]
Hi Walter,

The first one from the list (Single Client) did not work for me. After
installing it, I could see Spotify on idrive but couldn't navigate to the
app. Clicking in the Spotify option even multiple times, on the iDrive
screen did nothing. So, this version did not work at all and I couldn't
play any songs.

The second version (newer Spotify SDK) worked flawlessly. I could navigate
to Spotify, select songs. Every time, I started the car the phone was
connected to the app, play Spotify automatically and after getting out of
the car, the app and Spofity both got disconnected (no persistent Spotify
notification). I tried this version almost 10 to 12 times and it connected
and disconnected perfectly each time and it worked.

Please let me know if you need any logs or more information. Cheers.

**Comment by hufman** [comment]
Excellent, thank you so much! I've merged the updated Spotify SDK to the main build and hope that's enough.
@fabssor have you experienced this Spotify issue on recent builds since Saturday?

**Comment by fabssor** [comment]
Ah wanted to write you yesterday but forgot...
No, since the newest builds it seems to be good!
One sidenote which leads me to believe this is also a Spotify issue: On Saturday the same happened with Maps. Maps were closed but still, Spotify did show the notification that Google Maps is connected.

**Comment by hufman** [comment]
Excellent, I'm glad to hear it! I'll mark this issue as resolved.
