### ISSUE TITLE
Minor fixes for ID6 Media\Radio Tile in "AudioPlayer" Mode

### ISSUE THREAD

**Issue by berseker** [hufman/AndroidAutoIdrive#251]
I post here in order to keep track of the request, some time ago discussed on the chat.
If the request is not technically possible, feel free to close the issue obviously :D

I think it should be a nice fix to show Artist\Song icons & the coverart if possible using "AudioPlayer" legacy mode on ID6 systems.

Moreover when an "Artist" field in an MP3 song is too long, it should be "truncated" instead of occupying the complete text space available on the tile (see "audioplayer" part of the screenshot compared to a similar case on the "spotify" mode)

the "spotify" song ID3 tag is
artist David Guetta & Sia
song Flames

the "audioplayer" song ID3 tag is
artist David Guetta & Chris Willis
song Love Is Gone

I add below an image showing what i mean
![image](https://user-images.githubusercontent.com/1159431/114607832-4963ae00-9c9d-11eb-89ed-1795568d9925.png)

**Comment by LACNR** [comment]
The Audioplayer ist only used to Image what you wanna use on first connection, you select the App and then AudioPlayer, after that you can directly switch/select the app from the list without the need of AudioPlayer.

What you mean with Audioplayer legacy mode?

Also, if you use the old Connected Classic App it also adds an Audioplayer which unfortunatly is not working with newer Android phone (at least no audio via USB) because Android removed the protocol years ago. Maybe you select the wrong Player although it does show everything in ID4 (2016 LCI).

**Comment by bogdan-calapod** [comment]
@LACNR  what @berseker is referring to is the old `Audioplayer` interface (which is used on iDrive <4 I think ?) that is a fallback for apps that for some reason don't support the new Spotify-like UI.

@berseker if I remember correctly AAID has no control over that widget unfortunately :( I also opened an issue similar to this a couple months ago, but the solution to that was the new Spotify-like UI. If I recall correctly from `gitter` you said that the app you're using doesn't support that view, right ? Or was it that you just prefer the old view ?

**Comment by berseker** [comment]
@bogdan-calapod during chat discussion I confirmed that I personally prefer the "AudioPlayer" Full screen view instead of the "spotify" one since on the latter there are basically two big "touch buttons" for previous & next song that are supposed to be clicked on touchscreens, but that takes a very big part of the screen. I do recall that the "audioplayer" BMW app basically cannot be modified in its behaviour, I do not know if maybe could be interesting to create a "custom" AAI view for Music that can take advantages from both "Spotify-like" view & legacy AudioPlayer view. I am not a programmer but since it is possible to show a fullscreen picture of a Google Maps map, maybe it could be not so hard to create a simple widget showing a fixed cover art & some text strings.. :D

**Comment by berseker** [comment]
@LACNR basically since I use a simple MP3 player for listening to my music, I can select the "spotify" mode which basically works exactly as Spotify, or also on ID6 systems the MP3 Android app is working through the "Audioplayer" Bmw app (also called "legacy" since it works also on ID4 systems)

**Comment by bogdan-calapod** [comment]
That does sound doable for the main screen, but the home screen widget you posted a picture of it might not be possible, as from what I understand the car doesn't expose that API anywhere, so AAID can't do anything about it - but I think @hufman can give us more insight into that.

**Comment by LACNR** [comment]
I'm still confused what the Spotify-like view means in your wording, also "Spotify" mode is confusing me too though I guess you mean when you select an streaming app after selecting AudioPlayer.

Wait, I probably understood you cause when using an USB Stick/MP3 Player or Standard Music Player you basically have a similar interface as if you would use Spotify, Apple Music, iHeartRadio and so on because playing Audio via storage device is supported by BMW without the need of an additional app.

I'm still not understanding your problem I could be thinkin wrong, I see in your picture using Spotify shows everything correct on the home widget, but when using an USB Storage device or the Standard Music Player installed on your phone it doesn't?

**Comment by hufman** [comment]
Good morning!
I believe Audioplayer and Spotify mode refers to the two ways that AAI can log in to the car and present the music interface. Spotify mode is (afaik) not supported in ID4, but provides better integration in the car and matches the other music sources in ID5 cars such as Bluetooth and Radio. Audioplayer mode has a fixed positioning that does not expand to fill higher-resolution screens. @berseker would you mind posting comparison pictures of the two modes' main screens as examples of the differences?

Audioplayer mode only has a minimal integration to the rest of IDrive: There is a multimediaInfo event that allows for posting 2 text lines to the car, which is displayed in the Multimedia sidebar and (in ID5) the homescreen music tile. (Internally, BMW Connected names these lines as Title/Artist, but the car itself has no semantic meaning to these lines, and in fact AAI uses them in a backwards order compared to BMW Connected)
Spotify mode instead has a full semantic model: Instead of a generic image widget that happens to be in the right place in the main screen, it has a named coverart image widget that is displayed at the right place in the main screen _and_ also is displayed in the Multimedia sidebar and the homescreen music tile. Similarly, the semantic Artist, Album, and Title fields are used to populate related labels in the sidebar and music tile.

These are the only ways to add metadata to be shown in the rest of the car interface. If the app is running as Audioplayer, it does not have the semantic model to update coverart or the artist/album labels in the media tile. There is no other access to the car's tile widgets.

The only solution I see is to run the app in Spotify mode, but have the Spotify menu icon open the legacy Audioplayer layout (which does still exist, currently unused, in the Spotify app layout). There would be a slight performance penalty from updating both sets of label values, so it would have to be a non-default advanced option.

**Comment by berseker** [comment]
here are the screens:
1) Audioplayer Mode "fullscreen"
![PXL_20210415_155929517](https://user-images.githubusercontent.com/1159431/114910067-be5df180-9e1d-11eb-8a61-9988289e1ef1.jpg)
2) Audioplayer Mode "reduced"  when in splitscreen mode (same as fullscreen on 6.5" screen)
![PXL_20210415_155916502](https://user-images.githubusercontent.com/1159431/114910154-d6357580-9e1d-11eb-9aa1-37708877e400.jpg)
3) Spotify Mode "fullscreen"
![PXL_20210415_160030746](https://user-images.githubusercontent.com/1159431/114910217-e77e8200-9e1d-11eb-9482-91818b9c3867.jpg)
4) Spotify Mode "reduced" when in splitscreen mode (same as fullscreen on 6.5" screen)
this mode shows at first, the first image, and after a few seconds fades into the "coverart" view
![PXL_20210415_160041654](https://user-images.githubusercontent.com/1159431/114910315-08df6e00-9e1e-11eb-9543-6dafebff0142.jpg)
![PXL_20210415_160049429](https://user-images.githubusercontent.com/1159431/114910327-0d0b8b80-9e1e-11eb-8192-e1b7ac529810.jpg)

sorry for the screen dirty :D

**Comment by dlmarien** [comment]
Hello. I have an odd issue to report. In the Audioplayer mode the track time overlaps the progress bar. That issue has always existed when using the Audioplayer app. I read now that this is not fixable but wanted to share nonetheless. Just recently the Spotify app simply doesn't work any longer and forced to use the Audioplayer app. When I attempt to select the Spotify app, it just "spins" and defaults to the Audioplayer app. Some info: 2020 X3M, vehicle software date is March 2020, Android 11, Pixel 3XL, BMW Connecteddrive 6.4x, Android Auto Idrive 1.2.2 and MyBMW 1.3.4 and Spotify 8.5.64.1046. I have no idea why Spotify app no longer works...a bit on the frustrating side. Other possible pertinent info: I have deleted the BT connection on my mobile, the vehicle and have also deleted and reinstalled Connecteddrive, AAI and MyBMW and reconnected everything....still no luck. 
![Pic 1](https://user-images.githubusercontent.com/78308899/116818375-fd3bb900-ab38-11eb-993d-8746049cffca.jpg)
![Pic 2](https://user-images.githubusercontent.com/78308899/116818378-ff9e1300-ab38-11eb-8a99-d40f396b5bf4.jpg)

**Comment by waldemar-szostak** [comment]
I confirm it: I also can no longer use the Spotify app as the audioplayer seems to overlap it.

**Comment by berseker** [comment]
try to not use togheter MyBMW app & ConnectedDrive app (use one or the other only, without having them both installed simultaneously) . This may not be related to your issue but it is generally suggested in order to avoid potential ones

**Comment by dlmarien** [comment]
@berseker thanks for the added input. Sadly, I have tried combinations of both apps, the new MyBMW app and the Connecteddrive app either together or separately. If the Connecteddrive app is removed, I get nothing, not even the Audioplayer app. As soon as I re-install the Connecteddrive app, the Audioplayer app reappears. I can find no combination that will either address the track time/progress bar (although, your post clearly does not have that issue??), or have the Spotify app appear, at least without it trying to the "Loading app..." when the Spotify icon is selected. I'm stumped! The Spotify app had been working a little more than a month ago, now nothing. I guess I can live with the Audioplayer app, but that track time/progress bar piece is pretty strange given it doesn't seem to be affecting your screen?

**Comment by dlmarien** [comment]
@waldemar-szostak - thank you for you post. At least I'm not the only one!

**Comment by hufman** [comment]
That's a curious bug indeed! I have no idea why it would be mispositioning like that. It's probably some slight incompatibility with the ID4 Audioplayer layout on your newer infotainment.

AndroidAutoIdrive 1.2.2 does not fully support MyBMW, please install the [latest build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-master-nomap-sentry-release.apk) to fix this. This will allow AndroidAutoIdrive to run with either BMW Connected or MyBMW.

May I ask why you are running Spotify 8.5.64? This version of Spotify is still supported by the official BMW Connected app, and AndroidAutoIdrive (by default) will run as Audioplayer if this older Spotify is detected. As confirmation, this official Spotify icon will go away if you remove BMW Connected. This means that the Spotify icon you are seeing in the menu is the official Spotify app, and so the loading spinner is showing a problem starting the official Spotify app itself. If you upgrade Spotify, this official Spotify icon will go away, and then AAI will run in Spotify mode as shown above.

**Comment by dlmarien** [comment]
Hi @hufman thank you very much for this info. I have updated to the latest release per your post. With respect to why  running 8.5.64 - it was one of two or three older versions that enabled Spotify to work in my version of iDrive. Given what you've noted, I will update Spotify and retry. Again, thank you for all your efforts with this

**Comment by dlmarien** [comment]
@hufman ok, so...everything is now working as expected! The Audioplayer app is now gone (which is fine) and now Spotify app connects easily (tried 10 connects and got 9/10 ok connections! Google app is there as well now, which is was not as is the BMW Connected app, which also wasn't there. I'll leave both BMW apps installed on my mobile, just in case. Screen displaying correctly as well i.e. no overlapping or mispositioning. I updated to latest release of AAI as well as Spotify. Thank you again!

**Comment by hufman** [comment]
I posted a test build to add the option of using the legacy layout even with Spotify mode, [check it out](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/androidautoidrive-latest-legacy_audiostate-nomap-sentry-release.apk)!

**Comment by berseker** [comment]
On Monday ill try It for sure !😃

**Comment by berseker** [comment]
@hufman shortly tried it an hour ago, i think this option it's awesome :D  thank you. If i find some little bugs or anything similar, I'll surely report to you
