### ISSUE TITLE
App TuneIn Radio

### ISSUE THREAD

**Issue by STRYKER69** [hufman/AndroidAutoIdrive#344]
Was it possible to intrigue and support the app TuneIn Radio again?
This had worked before but with the current version, the app TuneIn is no longer listed.

**Comment by hufman** [comment]
Aa far as I know, TuneIn Radio wasn't working, at least for me. How did it work before? Did it support browsing and opening the app from closed, or just controlling the app if it's already running?

**Comment by STRYKER69** [comment]
It was displayed in the list and could be started.
Favorites did not work yet.
With the current beta, however, it is no longer displayed.

**Comment by hufman** [comment]
Very interesting!
The music app logic hasn't changed much, and the music app will show up in the car if it's already running.
You could try downgrading to an earlier version of the app or an earlier version of TuneIn, and see if that helps.

**Comment by STRYKER69** [comment]
You are right. With the current version 1.3rc2 TuneIn works if it was started before.
Also the station image is displayed. Favorites or next station do not work.
The same with DSAudio.
DI-FM Radio and Radio Tunes start themselves and work completely.
Can you add favorites to Tunein or DSAudio ?

**Comment by hufman** [comment]
AAI can only provide access to whatever functionality the music app allows, and Browsing is one of those types of features. If DSAudio or Tunein do not provide the MediaBrowserService permission to allow AAI to even start the app, it is not possible to add browsing support.
Please reach out to Synology to convince them to allow DSAudio to be browsed by other apps, especially since it is your NAS and your music. I am not a customer and don't have access to their support portal.
Also try to reach out to TuneIn for the same! But unfortunately it is up to them to enable this browse functionality for AAI, and it will automatically start working as soon as they update their app to allow browsing.
