### ISSUE TITLE
Saving a Spotify bookmark doesn't work properly

### ISSUE THREAD

**Issue by ahershey21** [hufman/AndroidAutoIdrive#361]
I was playing with the presets while using AAI and found that I could set one to an AAI channel - everything but Spotify. To do this, I could only trigger it when the list of all channels were present. I would highlight one of the channels and then press and hold the preset. I have now done this for multiple presets.

The only one that doesn't work is Spotify. I assume that this is due to this being the primary driver for the other channels.

This is more of an observation to explore, but could be an additional feature to develop in the future. 

Thanks again for all your efforts.

**Comment by hufman** [comment]
Can you clarify what you mean by "presets" and "channel"? If you mean, the hardware bookmark (what BMW calls them) buttons underneath the display, and the music app icons under the Media menu, I understand you.
Spotify should work as a bookmark entry, because saving the previous Audioplayer icon as a bookmark entry worked fine in my previous ID4 car. Granted, I haven't checked with Spotify because the Media shortcut icon by the controller works in ID5.

When you say "doesn't work", does it properly open the music interface, but that you'd prefer that it changes the music source to Spotify? The Spotify icon is indeed handled differently, precisely because the Media button effectively clicks the Spotify icon, so the app watches to make sure the Media menu is open for a few seconds as a signal that the user intends to change the source, and isn't just the shortcut.

If I understand your request properly, it should be doable to enable the Spotify icon, when saved as a Bookmark button, to switch the music source to Spotify, while allowing the Media button to function as it does now.

**Comment by ahershey21** [comment]
Yes, you got it right. The buttons (7 of them on my 2019 530e) are the ones
I hold to remember a function and then can press to repeat later (like the
old car radios that returned to the preset radio channel).

The music app icons are when you choose the media button, it list all the
media options. With AAI, Spotify is checked, but if I I highlight one of
the options that AAI brings in, I can then use the buttons to set this
option. In this way, I can jump from one to the other.

For example, if I run AAI and it finds my audio book player (Smart
Audiobook Player) - I pre set that to #2, Spotify is #1. I can then do the
same for Podcast to #3 and Youtube Music to #4. The car usually starts on
Spotify, but I can just press #2 and listen to my audiobook.

The only issue I have found is that I have to have the app actively running
on my phone. It doesn't seem to wake up the app from the BMW or AAI.

So it is not just Spotify that can be selected, but any of the audio
sources that Spotify enables.

Not really sure if there is anything to do at your end, but one thought was
to have the AAI wake up the apps on the phone (or user defines what apps to
wake up whenever AAI connects. Not sure if this is doable, but it would
make it so that you could switch back and forth between sources (apps on
Smartphone) from the buttons.

**Comment by hufman** [comment]
Thank you very much for the suggestion! I've pushed a fix to allow the Spotify bookmark to change the music source similar to the other app icons.
As for Smart Audiobook Player and Youtube Music, they reject attempts for AAI to launch them, and AAI can't work around that. Please contact support for the music app to request that the music app's `MediaBrowserService.onGetRoot()` be changed to allow AAI to connect and launch the app.

**Comment by ahershey21** [comment]
Thanks. I'll try to contact both and let you know.

**Comment by ahershey21** [comment]
I checked with Smart Audiobook Player. The author said due to an initial
poor design it was not possible.

As an aside, it is all working great for me switching apps with the preset
buttons, as long as I activate themselves on my phone. So for now, all is
good.
