### ISSUE TITLE
Use the Spotify/Bluetooth UI for AudioPlayer apps

### ISSUE THREAD

**Issue by Alapwood** [hufman/AndroidAutoIdrive#365]
It would be great if we could have the option to use the full UI for AudioPlayer apps instead of the mini player (I think that's what it's called).

Using Tidal for example works fine but I find myself just using the car's built in bluetooth UI because it has a better layout (much like AndroidAutoIdrive's Spotify layout) than the mini player.

This would make the UI for AudioPlayer apps better than the car's built in bluetooth UI because the album art would come through 🤩

**Comment by hufman** [comment]
I'm glad you like it!
If AAI is running in Spotify mode instead of Audioplayer mode, any music apps that AAI provides will be available in the same upgraded Spotify layout, including Tidal. It shouldn't run in Audioplayer mode if Spotify mode is enabled, is that different than what you experience?
Perhaps the wording might insinuate that it only works for Spotify. In fact, it does require logging in to the car as Spotify, but other music apps will be displayed in the same single interface.
There's an advanced option to always force the Spotify layout, but that will force a Spotify icon to show up in the car even if Spotify isn't installed, and so the autodetection logic would normally not use it to prevent confusion.
Unfortunately, it seems BMW never released the classic Audioplayer app with support for the ID5 AudioHmiState which includes the global coverart, so the only way to use this feature is to piggy-back on the few existing apps: Spotify, iHeartRadio, or Pandora.
I share your sentiment that the new Spotify layout is better than the legacy Audioplayer layout, and I particularly enjoy that it matches the other music sources in the car. AAI will definitely use the Spotify layout for all available apps, not just Spotify, if it is enabled. What are you seeing instead?

**Comment by Alapwood** [comment]
Haha, it's so obvious now, that makes total sense!

Thanks for taking the time to explain it, you've made my day 🙌
