### ISSUE TITLE
No visible app

### ISSUE THREAD

**Issue by fata74** [hufman/AndroidAutoIdrive#37]
Hi, I have a bmw f45 from 2017.
I have a problem, when I start the app on the vehicle I only see the Youtube app and nothing else (spotify or anything).
Why??
Sorry for my bad english.

**Comment by jezikk82** [comment]
Hi I can confirm the same issue. 
I have Google, Youtube, Spotify, Samsung Music listed in the phone. 
In the can in media I only see Youtube and Audioplayer (and inside again I only see Youtube). 
(see attach photos).

Moreover, in Connected Drive menu I see  Audioplayer (with only youtube inside) and "Notofications" but only icon is present, no description. 




![20191008_180627](https://user-images.githubusercontent.com/7836767/66547108-cceb8e80-eb3e-11e9-9f2b-4c6252912b3d.jpg)
![20191008_180634](https://user-images.githubusercontent.com/7836767/66547111-cceb8e80-eb3e-11e9-8f9d-73fc9086735f.jpg)
![20191008_180640](https://user-images.githubusercontent.com/7836767/66547113-cd842500-eb3e-11e9-8dcb-01508c875517.jpg)
![20191008_180814](https://user-images.githubusercontent.com/7836767/66547114-cd842500-eb3e-11e9-9001-a3d0140cf92e.jpg)

**Comment by hufman** [comment]
Spotify no longer allows my app to connect and control it, you would need to install an [older version](https://www.apkhere.com/down/com.spotify.music_8.4.96.953_free) of Spotify. Google Music and Samsung Music similarly don't allow my app to connect. In the README you'll find a list of known compatible apps, please try one of them!

The Notifications menu has a blank label on purpose. Because of how I'm reusing application certs to log in to the car, I don't have control over the main entrybutton's label, so I just choose to not show the label.

**Comment by jezikk82** [comment]
So maybe it'd be a good idea to gray out (or add some small text "incompatible") next to applications that are incompatible in the app instead showing them and allowing to press. This is confusing.

**Comment by fata74** [comment]
Hi, I tried also with the old version of Spotify that you indicated but didn't see, only Youtube is visible.

**Comment by hufman** [comment]
I will consider UI improvements, thanks! The only clue right now is the little play symbol in the app, which isn't very clear.
I have an idea for a future version to get control over more apps anyways, we'll see whether it's still needed.

After installing the older app, you might need to pull down to refresh the app list. It would automatically probe new apps, but it would have skipped Spotify if it had seen it already.
