### ISSUE TITLE
Can't get Connected Classic app to open 

### ISSUE THREAD

**Issue by KyrneDev** [hufman/AndroidAutoIdrive#45]
Both connected classic apps stay stuck on loading forever. I know this isn't a problem with your app but wanted to know if you had any tips to get it working

Galaxy s10 Android 10

**Comment by kgospodinov** [comment]
I have the same phone and os. So far everything is working fine. You could try to set the default usb mode to transfering file as well as turning the disable automatical usb audio routing on.

**Comment by hufman** [comment]
I apologize, I replied to @KyrneDev by email but left this issue open as a reminder for me to debug Connected Classic, for curiosity's sake.

The default usb mode shouldn't matter, as soon as the car identifies itself as an Android Open Accessory the phone will switch to Accessory mode. The USB Audio routing won't change anything either, with the new Androids not supporting the car's usb audio method.

The main trick is to go to Connection Assistant in the car and switch the phone to Accessory mode.
Another fun trick is that the main UI for the Connected apps doesn't matter: The USB Accessory interface for the apps run in the background, and so they'll continue to start up and handle app connections and let my app connect through them, even if the main screens are stuck. The Security Service that my app uses definitely works even without starting the apps at all. 

I'll keep this issue open, because I want to find out exactly why the Connected Classic screens aren't working, but purely for curiosity. They should still work anyways.

**Comment by bogdan-calapod** [comment]
I think this should be closed as well ? 😁

**Comment by hufman** [comment]
I agree, since Connected Classic isn't needed anymore
