### ISSUE TITLE
Add Mi Music to supported apps

### ISSUE THREAD

**Issue by jezikk82** [hufman/AndroidAutoIdrive#58]
Please add to list of apps mi music (default xiaomi music app).

**Comment by hufman** [comment]
Thank you for finding this supported app. Can you send me a link to the app on the Play Store, so I can add it to the README?
Thank you!

**Comment by jezikk82** [comment]
https://www.apkmirror.com/apk/xiaomi-miui/miui-music-player/

**Comment by hufman** [comment]
I can't seem to install the app from that link. Version 4.0 can't install `Package com.miui.player requires unavailable shared library miui-stat.jar; failing!`, and version 3.1 crashes because it can't find `android.provider.MiuiSettings`.
However, it was enough for me to find the main [Play Store link](https://play.google.com/store/apps/details?id=com.miui.player). I'll add it now.

**Comment by jezikk82** [comment]
The play store link is valid and app is correct. However, I still don't see that app in the list of apps in the main screen of the app. 

I have version 4.07.

**Comment by hufman** [comment]
When you said "It's working and can be controlled by the app but is not shown", what do you mean? The apps in the main ui show all the apps that implement the API I use, and the car app can't control the app unless it is in this list.

**Comment by jezikk82** [comment]
It's not shown in the app ui but when I start playing music from that app (muiu music) it shows empty item (olny icon) under audioplayer and when I go into that I see the screen with covers, control and rest.

**Comment by hufman** [comment]
Can you show me what you are seeing, and attach a picture?

**Comment by jezikk82** [comment]
![Screenshot_2019-12-24-15-25](https://user-images.githubusercontent.com/7836767/71416213-cd84c300-265f-11ea-8f61-95499f23490a.jpg)
![Screenshot_2019-12-24-15-09-53-096_me hufman androidautoidrive](https://user-images.githubusercontent.com/7836767/71416214-ce1d5980-265f-11ea-87f3-bec9d1ad7ed2.jpg)

**Comment by hufman** [comment]
Ah ha! Yes, that shows that the app is only controllable while it is running, I can't connect to it with the MediaBrowser API to start it or browse it. Is there some way I can make that more clear in the UI?

**Comment by jezikk82** [comment]
Maybe you can scan for the music app on the phone, show all of them with information as is now and add information that you have to start app manually.

**Comment by hufman** [comment]
The icons on the right are clickable and expand to explain what they mean. The dotted play icon says it is controllable while it is running. A new user additionally sees a button prompt to grant access to control active apps, which you might not have seen by upgrading from a previous version with the permission already.

I could do a scan to find other music apps (at least, those that are registered as responding to Media Buttons). However, since I can't connect to them until they start, I don't want to add them as options in the app selector until they are ready for control. As far as I know, any running music app is accessible with this new API, just as long as it's running. So, I don't think it's needed to show every app until it is running and available for control.

User interface design is tricky, and I'm handicapped by not having an outside perspective, so I value your opinions! Please let me know if this makes sense and if you have any more ideas for improvements!
