### ISSUE TITLE
Notifications: Scrolling not possible

### ISSUE THREAD

**Issue by masteralarm** [hufman/AndroidAutoIdrive#76]
It seems that it is not possible to scroll inside of notifications (buttons are greyed-out on ID4).
This happens often times with chat apps that stack the last messages, for example of a group chat.

Can the behaviour be changed in this app?

**Comment by hufman** [comment]
Thank you for reaching out, and for the detail about ID4! That gives me a good idea of what's probably happening:
IDrive4 implements a feature called Speedlock, which disables some screens from scrolling if the car is not parked. When the car is put into Park (or, Neutral with Parking Brake on a stickshift car), the scrolling should unlock.
If I try to disable the Speedlock setting, the screen stops toggling the enable/disable state based on the Parking gear. If the car is not parked (and thus scrolling is locked) when I disable Speedlock, the screen will be stuck in locked mode.
Due to this, I wait for the car to be in Park mode before disabling the Speedlock setting. However, there may be situations that I don't detect properly, and so the screen might continue to lock scrolling during drive, or I improperly disable Speedlock while the screen is already locked.

As a first test, which should almost always work: Put your car into Park with the Parking Brake, and then toggle the Enable Notifications switch off and back on in the phone interface. Your long notification should be scrollable in this mode.
Next, you should be able to shift to Neutral and release the Parking Brake, and the long notification should remain scrollable. If it switches to locked, then the app isn't properly disabling Speedlock for some reason.

What I hope is happening is that the app connects while the car is not in Parked, and the app is still watching for the car to Park so it can disable the Speedlock setting.
As a third test, if you encounter this Speedlock behavior while out on a drive, please try (safely, of course) dropping to Park gear and verifying that the notification becomes scrollable. The app _should_ detect this and disable Speedlock, and then the notification should remain scrollable as you continue to drive.

This limitation is specific to IDrive4: they removed this functionality in IDrive5 and all screens are scrollable in this newer version.

Please try these steps out and let me know the results!

**Comment by ziggythehamster** [comment]
Possibly unrelated, but pop-ups show up with only two lines (header and text) and the text gets truncated

**Comment by hufman** [comment]
Sadly, popups only support two lines of text, along with a title at the top of the screen. As part of #72, I fixed it to [show the last line of text](https://github.com/hufman/AndroidAutoIdrive/blob/554a9619/app/src/main/java/me/hufman/androidautoidrive/carapp/notifications/views/PopupView.kt#L48) for the next release.

**Comment by masteralarm** [comment]
I was able to verify the behaviour you described @hufman. It works when the car gets into P while the phone is connected via USB. Afterwards, scrolling also works while driving.

**Comment by hufman** [comment]
Perfect, thanks for confirming! I'll add it to the FAQ for the future.

**Comment by ziggythehamster** [comment]
FYI: This functionality can be disabled in Bimmercode by activating "Video in motion" in the basic menus inside the Headunit module. If this is not available for your car for whatever reason, or if you're coding using a computer, set whatever is appropriate to your car below:

```
Module HU_CIC or module HU_NBT -> Section 3000 -> SPEEDLOCK_X_KMH_MAX: Set to werte = FF
Module HU_CIC or module HU_NBT -> Section 3000 -> SPEEDLOCK_X_KMH_MIN: Set to werte = FF
Module HU_NBT -> Section 3000 -> VIDEO_SPEEDLOCK_CONDITION: Set to none
Module HU_NBT -> Section 3000 -> SERVICES_MESSAGES_SPEEDLOCK_CONDITION: Set to none
Module HU_NBT -> Section 3000 -> OFFICE_MESSAGES_SPEEDLOCK_CONDITION: Set to none
```

Note that these flags won't fully enable Video in Motion, which is disabled by default in countries where that's not universally legal, but it will configure your car to work like newer cars work in your market. BMW was apparently very conservative when it came to enabling this in countries which were just coming out with hands-free laws at the time. If you want VIM, use your favorite search engine for more details :).
